name: Auto PR & Merge Dev to Staging

on:
  push:
    branches:
      - feature/dev  # Runs when changes are pushed to `feature/dev`

jobs:
  test-and-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install 

      - name: Run tests
        run: npm run test

      - name: Create Pull Request to Staging
        if: success()  # Only if tests pass
        uses: peter-evans/create-pull-request@v6
        with:
          branch: feature/dev
          base: staging
          title: "Automated PR: Dev → Staging"
          body: "This PR was automatically created and will be merged if tests pass."
          labels: "automated, staging"
          draft: false

      - name: Auto Merge PR
        if: success()
        uses: pascalgn/automerge-action@v0.15.3
        with:
          merge_method: squash
          github_token: ${{ secrets.GITHUB_TOKEN }}
